webtalk_init -webtalk_dir C:\\Users\\Lenovo\\Desktop\\CESE\\CESE_MYS\\TP_Final\\Synthesis\\FIR_Filter_PSPL\\FIR_Filter_PSPL.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-06-14 13:41:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pclb4184d2rgnf6cus8u38oj0p" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-1235U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.891 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1718377350116" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.1" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1718377350116"
webtalk_add_data -client sdk -key uid -value "1718377373355" -context "sdk\\\\bsp/1718377373355"
webtalk_add_data -client sdk -key hwid -value "1718377350116" -context "sdk\\\\bsp/1718377373355"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1718377373355"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1718377373355"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1718377373355"
webtalk_add_data -client sdk -key uid -value "1718377374987" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key hwid -value "1718377350116" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key bspid -value "1718377373355" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key projSize -value "205.5078125" -context "sdk\\\\application/1718377374987"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1718383314667"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1718383314667"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1718383314667"
webtalk_add_data -client sdk -key DebugCount -value "21" -context "sdk\\\\bsp/1718383314667"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1718383314667"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1718383314667"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1718383314667"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1718383314667"
webtalk_transmit -clientid 1080604436 -regid "" -xml C:\\Users\\Lenovo\\Desktop\\CESE\\CESE_MYS\\TP_Final\\Synthesis\\FIR_Filter_PSPL\\FIR_Filter_PSPL.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Lenovo\\Desktop\\CESE\\CESE_MYS\\TP_Final\\Synthesis\\FIR_Filter_PSPL\\FIR_Filter_PSPL.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Lenovo\\Desktop\\CESE\\CESE_MYS\\TP_Final\\Synthesis\\FIR_Filter_PSPL\\FIR_Filter_PSPL.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
